### ISSUE TITLE
ReferenceError: ReactLayout is not defined

### ISSUE THREAD

**Issue by Scalahansolo** [kadirahq/meteor-react-layout#1]
In my very simple project located at https://github.com/Sylanz/react_meteor_test I am getting an Error that ReactLayout is not defined. Thought this was strange and should pass it along.

**Comment by arunoda** [comment]
That's was a lame error of not exposing the ReactLayout namespace.
Just pushed a new version :)

**Comment by arunoda** [comment]
Fixed this.
