### ISSUE TITLE
Using ES6 classes extending from React.Component doesn't work

### ISSUE THREAD

**Issue by ndarilek** [kadirahq/meteor-react-layout#10]
Fairly new to React so apologies if this is a silly question. I was experimenting with [this blog post](http://babeljs.io/blog/2015/06/07/react-on-es6-plus/) as a way to streamline some of my JSX. I had a component based on React.createClass, but then changed it to this:

class Add extends React.Component {

  newItem(event) {
    event.preventDefault()
    var titleNode = React.findDOMNode(this.refs.title)
    var title = titleNode.value.trim()
    Lists.findOne().$push({items: {_id: Random.id(), title: title, done: false}})
    titleNode.value = ""
    titleNode.focus()
  }

  render() {
    return <form className="form-inline" onSubmit={this.newItem}>
      <div className="form-group">
        <input className="form-control" type="text" ref="title" required/>
      </div>
      <button className="btn btn-default" type="submit">Add</button>
    </form>
  }

}

Now, nothing renders. I call it like so:

ReactLayout.render(Layout, {content: <Main/>, footer: <Add/>})

What am I doing wrong?

Thanks.

**Comment by rogchap** [comment]
This is an issue with the babel compiler / meteor with lack of support for the `export class` in ES2015. 

Your class `Add` is compiled to:

```
var Add = (function (React$Component) { .... }
```

which means it's a **local class**, and therefore cannot be picked up by ReactLayout.

To fix you need to place your `Add` class into the global namespace:

```
Add = class Add extends React.Component { .... }
```

**Comment by arunoda** [comment]
Closing this since, this is not related ReactLayout and we've perfect answer. Thanks @rogchap

**Comment by PEM--** [comment]
Wow, thanks @rogchap. I was asking Google the same question and found your clever answer.

PS: Sorry @arunoda for using this issue to thank @rogchap.

**Comment by mtsewrs** [comment]
Awesome, thanks!

**Comment by hafeez1042** [comment]
+1

**Comment by jyjunyz** [comment]
nice
