### ISSUE TITLE
Adding React Components using api.addFiles

### ISSUE THREAD

**Issue by churcho** [kadirahq/meteor-react-layout#13]
Is there any reason why ReactLayout doesn't doesn't seem to be able to render files added within a package using the api.addFiles method?

```
api.addFiles(['components/router.jsx','components/base_components.jsx'],['client', 'server']);
```

**Comment by arunoda** [comment]
You need to add ReactLayout to this package as well. Or you need to expose these components out from the package.

Can't tell more without looking at the app or a sample repo.

**Comment by churcho** [comment]
Perfect. Oversight on my end. It's working perfectly.
