### ISSUE TITLE
Using multiple Layouts

### ISSUE THREAD

**Issue by brandonmikeska** [kadirahq/meteor-react-layout#14]
Hey I don't see how to properly use multiple layouts. I have two layouts, but when using Flow Router to change the URL and try to load the new layout, it works but then gives this message:

`Warning: render(): Target node has markup rendered by React, but there are unrelated nodes as well. This is most commonly caused by white-space inserted around server-rendered markup.
react-runtime-dev.js?8fefd85d334323f8baa58410bac59b2a7f426ea7:21998 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <body class="pushable
 (server) <header data-reactid=`

And eventually this:

`Exception from Tracker recompute function:
Error: Invariant Violation: ReactMount: Root element ID differed from reactRootID.`

What is the proper way to change layouts between pages?

**Comment by arunoda** [comment]
Can I have a sample app for this?

**Comment by brandonmikeska** [comment]
@arunoda actually I figured it out. It appears the structures weren't the same so it couldn't diff the two doms. So I made sure that both layouts had an outer <div> with a <main> inside. Now it works. Thank you!
