### ISSUE TITLE
How to use ReactLayout.render to target specific dom elements?

### ISSUE THREAD

**Issue by tetratorus** [kadirahq/meteor-react-layout#15]
I would like to be able to do something like this:

``` javascript
React.render(<App />, document.getElementById("render-target"));
```

Is it possible to do this using ReactLayout.render?

**Comment by arunoda** [comment]
It's not possible. If you need something like that, simply use `React.render`. If you are using it inside FlowRouter wait for the DOM. See: https://github.com/kadirahq/meteor-react-layout/blob/master/lib/react_layout.js#L42
