### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by churcho** [kadirahq/meteor-react-layout#16]
How can I render a loading template while the current one is loading. I would like to have a preloader on each route (not specifically tied to mongo collections but let's say on assets load or page reload).

**Comment by arunoda** [comment]
I think this is not specific to this project. Would you mind asking this on
meteor forums.

**Comment by churcho** [comment]
I actually meant to ask this on FlowRouter since I am using it with ReactLayout. My bad!
