### ISSUE TITLE
where to put head/ meta tags etc

### ISSUE THREAD

**Issue by dcsan** [kadirahq/meteor-react-layout#17]
If i want to use this _without_ blaze, where do i put the base things like `<meta>` tags, and content that usually goes into the `<head>` ?

i tried adding into a layout component, but it gets rendered inside the body it seems.

![image](https://cloud.githubusercontent.com/assets/514002/9706357/7ea559aa-5497-11e5-8af6-31a0bf33144a.png)

```
MainLayout = React.createClass({

    mixins: [],

    render() {
        return (
            <html>
            <head>
                <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </head>

            <body>
            <div id="layout">
           ...
```

**Comment by arunoda** [comment]
There is a package called static-html which allows you to put static content

Or if you wanna set it dynamically, use kadira:dochead package.

**Comment by dcsan** [comment]
this is not so much about static content, but just where to put a file for adding headers to the layout?

it seems the React renderer will render always somewhere inside the body tag?

so we still need Blaze just to add some headers? I'm trying to get my client side size reduced (for mobile devices on 2.5G), so having two front-end UI frameworks loaded seems like a bad idea...

**Comment by arunoda** [comment]
I hope then both of suggestions works for you.

**Comment by dcsan** [comment]
i tried static-html and was able to drop an .html file into the client directory, and the meta headers came out. thanks very much!
