### ISSUE TITLE
Can't comment code in layouts

### ISSUE THREAD

**Issue by karldanninger** [kadirahq/meteor-react-layout#19]
```
<p>This is visible</p>
<!-- This raises an 'Unexpected Token' -->
/* This is visible */
// This is also visible

```

Is there a way I can add inline comments to react templates?

**Comment by arunoda** [comment]
This is something in React. You can comment like this:

```
{// my comment is here}
```

**Comment by karldanninger** [comment]
Thank you for your swift reply!

PS, that doesn't seem to work on the same line. I had to break the comment on to a separate line. :fearful: 

```
{
    // my comment is here
}
```
