### ISSUE TITLE
Multiple <head> and <body> tags

### ISSUE THREAD

**Issue by v3rron** [kadirahq/meteor-react-layout#22]
Hey I just updated to new version 1.4.0 and multiple <head> and <body> tags appearing on my app, which breaks it entirely.
<img width="636" alt="screen shot 2015-10-16 at 00 46 19" src="https://cloud.githubusercontent.com/assets/1641115/10534041/a40cdef8-739f-11e5-9794-d5c0577a3758.png">

PS: it was working fine just before the update.

**Comment by arunoda** [comment]
Are you using Flow Router or Flow Router SSR?

**Comment by arunoda** [comment]
Okay. I can confirm this. Working on it.

**Comment by arunoda** [comment]
Update now. I fixed it.

**Comment by v3rron** [comment]
Thanks @arunoda
