### ISSUE TITLE
react-root

### ISSUE THREAD

**Issue by satyavh** [kadirahq/meteor-react-layout#24]
I found out via an issue, but the docs don't mention that your root element should have an id="react-root", otherwise all this doesn't work. Because you can name your root element anything you want.

`<div id="react-root"></div>`

You might want to add that.

**Comment by arunoda** [comment]
ReactLayout automatically, create the root element. You don't need to do it manually.

**Comment by satyavh** [comment]
I see. Ok that's great. But that wasn't clear either. 
Awesome package btw!
