### ISSUE TITLE
Pass callback to layout?

### ISSUE THREAD

**Issue by nicholasalanbrown** [kadirahq/meteor-react-layout#26]
I love this package, but most React layout examples I've seen use a global `<App />` container component which allows you to pass callbacks to it. Is there a way for me to pass callbacks to the layout component? I'm trying to trigger open/closing a menu that needs to sit outside of the main content and header, and I can't figure out how to bubble up the toggle event to the layout then back down to the `<Menu />` component. 

My layout looks like this: 

```
C.MainLayout = React.createClass({
    showLeft: function() {
        this.refs.left.show();
    },

    showRight: function() {
        this.refs.right.show();
    },
    toggleMenu: function () {

    },
    render() {
        return (
            <div className="full-height">
                <C.Menu ref="right" alignment="right">
                    <C.MenuItem hash="first-page">First Page</C.MenuItem>
                    <C.MenuItem hash="second-page">Second Page</C.MenuItem>
                    <C.MenuItem hash="third-page">Third Page</C.MenuItem>
                </C.Menu>

                {this.props.header}

                {this.props.content}

                {this.props.footer}
            </div>
        )
    }
});
```

I want to trigger a callback from a button click in the rendered header component back up the layout and down to the menu to update it's state....

**Comment by arunoda** [comment]
Quite not sure, what you wanna do. `ReactLayout.render` is very similar to `React.render` in the API wise. So, you can do anything.

I hope you can use a callback as a react component prop.

**Comment by arunoda** [comment]
This seems like a question to me. Try to post into Meteor Forums where a lot of can answer.
