### ISSUE TITLE
how to add head / meta fields?

### ISSUE THREAD

**Issue by dcsan** [kadirahq/meteor-react-layout#30]
I want to add some custom fields so this will render properly on a mobile device.

eg like (jade)

``` jade

head
  //- this is critical for mobile and emulation to look and work properly
  title SuperSite
  meta(name='viewport', content='width=device-width, maximum-scale=1, user-scalable=no')
  meta(http-equiv="X-UA-Compatible" content="IE=edge")
  meta(charset="utf-8")
  //- link(rel="shortcut icon" href="/assets/ico/favicon.png")

```

**Comment by arunoda** [comment]
If this is static. You can use https://atmospherejs.com/meteor/static-html and create a simple .html file with the head tag.

If you need dynamic metadata, you can use DocHead: https://github.com/kadirahq/meteor-dochead
