### ISSUE TITLE
how to add React add-on components

### ISSUE THREAD

**Issue by dcsan** [kadirahq/meteor-react-layout#31]
some features of React are broken into components, for example the rather critical for animation 
ReactTransitionGroup
http://facebook.github.io/react/docs/animation.html
http://facebook.github.io/react/docs/component-specs.html

How can these be added to a react-layout project?

```
var ReactCSSTransitionGroup = require('react-addons-css-transition-group');
```

usually the code has a require. perhaps we can just use npmRequire and it will find the package in npm?

also:
https://www.npmjs.com/package/velocity-transition-group

**Comment by arunoda** [comment]
Actually, this is not react-layout specific. It's about adding it to your app.
You can do it with browserify: https://react-in-meteor.readthedocs.org/en/latest/client-npm/

But I don't have any experience on adding these animation packages. May be better to ask on Meteor Forums. I hope there will be much better people, who can discuss more.

**Comment by dcsan** [comment]
ok thanks!

**Comment by dcsan** [comment]
in case anyone else comes here - animations package is already included in meteor's react build
https://forums.meteor.com/t/react-js-addons-for-transitions/7025

![image](https://cloud.githubusercontent.com/assets/514002/10804549/047354a8-7e03-11e5-9197-61a1f5e552de.png)

**Comment by arunoda** [comment]
Nice.

**Comment by ghost** [comment]
I'm using Meteor 1.4 and here what is required for that version.

install additional package in meteor: 
- meteor npm install --save react-addons-transition-group
- or
- meteor npm install --save react-addons-css-transition-group

then at the top of you jsx file you need the following import:
- import ReactTransitionGroup from 'react-addons-transition-group';
- or
- import ReactCSSTransitionGroup from 'react-addons-css-transition-group';

This MeteorChef article helps a lot https://themeteorchef.com/snippets/react-css-transition-groups/

And I had a hard time figuring out why the componentWillEnter and componentWillLeave were not called. Make sure your ReactTransitionGroup is always rendered. This is the only way to get those notifications when you render more or less components inside the ReactTransitionGroup.

Don't do that:

```
                                {this.data.xpPortfolios.map(function(pPortfolio, index){
                                    return (
                                        <ReactTransitionGroup
                                            key={ index }
                                        >
                                            <ReactPortfolioCard
                                                Portfolio={pPortfolio}
                                            >
                                            </ReactPortfolioCard>
                                        </ReactTransitionGroup>
                                    );
                                },this)}
```

Do That:

```
                            <ReactTransitionGroup>
                                {this.data.xpPortfolios.map(function(pPortfolio, index){
                                    return (
                                            <ReactPortfolioCard
                                                key={ index }
                                                Portfolio={pPortfolio}
                                            >
                                            </ReactPortfolioCard>
                                    );
                                },this)}
                            </ReactTransitionGroup>
```

In the example above, any object that already exist in the array this.data.xpPortfolios, will fire componentWillAppear but not componentWillEnter. For any object added after initial rendering it will fire componentWillEnter. For any object removed after the initial rendering it will fire componentWillLeave.

Hope it can help anybody. 

And also make sure you call the callback.

```
componentWillAppear: function(callback){
    console.log('componentWillAppear');
    callback();
},
componentDidAppear: function(){
    console.log('componentDidAppear');
},
componentWillEnter: function(callback){
    console.log('componentWillEnter');
    callback();
},
componentDidEnter: function(){
    console.log('componentDidEnter');
},
componentWillLeave: function(callback){
    console.log('componentWillLeave');
    var pThis = ReactDOM.findDOMNode(this);
    if (pThis != null) {
        $(pThis).slideUp('fast', function () {
            callback();
        });
    }
},
componentDidLeave: function(){
    console.log('componentDidLeave');
},
```
