### ISSUE TITLE
Unexpected token < in route render

### ISSUE THREAD

**Issue by theruther4d** [kadirahq/meteor-react-layout#35]
I'm trying to render a react component from the router, but I'm getting the error `SyntaxError: Unexpected token <`. I'm probably just doing something silly, but I followed the example in the docs and it doesn't want to cooperate. 

routes:

```
var admin = FlowRouter.group({
    prefix: '/admin'
});

admin.route( '/', {
    action: function() {
        ReactLayout.render( MainLayout, {
            content: <AdminArea />
        });
    }
});
```

**Comment by arunoda** [comment]
You may be need use `.jsx` as the file extension :)

**Comment by theruther4d** [comment]
Thanks, finally realized that as soon as I hit submit :) Coding too late makes me crazy. Thanks for the help!

**Comment by junibrosas** [comment]
DANG!!!! I spent hours for this.
