### ISSUE TITLE
Issue using ReactLayout.render

### ISSUE THREAD

**Issue by mehdimahmoudi** [kadirahq/meteor-react-layout#38]
Hi, sorry for posting this question here. Wasn't quite sure where was the best spot to post it.

While trying to pass a React component to the main layout content prop, I get "SyntaxError: Unexpected token <"

I tried to follow the guide in this repo. Note that I don't get the error if I user a simple string like "Hello" in content: . It renders and displays Hello correctly. 
Thanks for your assistance!

My default route:
FlowRouter.route('/', {
    name: 'Home',
    action: function(params) {
        ReactLayout.render(MainLayout, {content: <Home welcome="Hello" />});
    }
});

My MainLayout (exactly like the guide):
MainLayout = React.createClass({
    render() {
        return(
            <div>
                <header>

```
            </header>
            <body>
                {this.props.content}
            </body>
            <footer>

            </footer>
        </div>
    );
}
```

});

My Home component:
Home = React.createClass({
    render() {
        return (
            <div>
                <h1>{this.props.welcome}</h1>
            </div>
        )
    }
});

**Comment by mehdimahmoudi** [comment]
I am adding an image of the code to avoid the markdown of GitHub...

![image](https://cloud.githubusercontent.com/assets/209687/11283079/25caaee2-8f03-11e5-870e-2a8eaba82063.png)

**Comment by monocursive** [comment]
It might be that your router file is has a .js extension instead of .jsx

**Comment by mehdimahmoudi** [comment]
That was exactly that!
Merci @maz-dev :)

**Comment by jpdatalicious** [comment]
Thanks @maz-dev !
