### ISSUE TITLE
ReactLayout renders app twice

### ISSUE THREAD

**Issue by tyusupov** [kadirahq/meteor-react-layout#39]
Hi Arunoda,

I'm experiencing a weird issue with ReactLayout where it renders the same app twice.

Repo with all code is here:
https://github.com/tyusupov/meteor-react-layout-issue

Some details
1. 2 React Apps are created
![react](https://cloud.githubusercontent.com/assets/46284/11321023/7ab82404-907d-11e5-97d5-d883b7810be4.png)
2. These apps are mounted on 2 divs myapp (expected) and react-root (unexpected).
3. Content is displayed twice as well.
![divs](https://cloud.githubusercontent.com/assets/46284/11321022/7ab625be-907d-11e5-80f7-1e1aeb09449b.png)

If FlowRouter block is uncommented in main.jsx then everything works as expected.

If ReactLayout is replaced with ReactDOM apps are rendered just once, which leads me to believe the issue is with ReactLayout.

Thank you very much in advance for looking into it,

Telman

Here is the code:

```
main.html
-------------------------------
<head>
    <title>My App</title>
</head>
<body>
    <div id="myapp"></div>
</body>

main.jsx:
-------------------------------
App = React.createClass({
    render() {
        return <ContentPage />
    }
});

ContentPage = React.createClass({
    render() {
        return <div>This is ContentPage</div>
    }
});

FlowRouter.route('/', {
    action() {
        ReactLayout.render(App);
    }
});

if (Meteor.isClient) {
    Meteor.startup(function () {
        ReactDOM.render(<App />, 
            document.getElementById('myapp'));
    });
};
```

**Comment by tyusupov** [comment]
Having looked at the code at react_layout.js, am I using it correctly? Does it expect the root node of my app to be named 'react-root'?

**Comment by Vaqxin** [comment]
Not sure if you still need this answer but your problem is  

if (Meteor.isClient) {
    Meteor.startup(function () {
        ReactDOM.render(<App />, 
            document.getElementById('myapp'));
    });
};

Remove that and your app should only render once.

**Comment by arunoda** [comment]
@tyusupov @Vaqxin has given the answer. Thanks.

**Comment by tyusupov** [comment]
Thank you very much for looking into this!

If I remove this code, how would I attach the react application to a specific DOM element - 'myapp' in this case? However, if no one else has the issue, please don't follow up anymore and keep this issue closed  - I moved on to react-router a while ago.

**Comment by gauravChaturvedi** [comment]
I'm facing the same issue but with react-router.. anyone know the solution ?
