### ISSUE TITLE
jQuery as dependency?

### ISSUE THREAD

**Issue by gabrielhpugliese** [kadirahq/meteor-react-layout#4]
`Meteor.defer` inside `Meteor.startup` didn't work?

**Comment by arunoda** [comment]
I didn't try it frankly.
Just wanted to make sure, it's working properly. Need to give that update.

**Comment by maartenbusstra** [comment]
Can you please refactor out the jQuery dependency? Now we can remove Blaze and jQuery, with the new static-html setup, it's kind of sad I have to keep jQuery in for this small lib.

**Comment by arunoda** [comment]
Okay. Got it. I will work on it.

**Comment by maartenbusstra** [comment]
Awesome! And thanks for the great packages! :)

**Comment by arunoda** [comment]
Check now, we no longer use jQuery :)

**Comment by maartenbusstra** [comment]
@arunoda Nice job!
