### ISSUE TITLE
<link> and <meta tags>?

### ISSUE THREAD

**Issue by nicholasalanbrown** [kadirahq/meteor-react-layout#5]
Hello:

I'm trying to follow the HTML5 boilerplate and I can't figure out how to properly include the <link> and <meta> tags via JSX. Here's my layout code:

```
// layout.jsx
MainLayout = React.createClass({
  render() {
    return <div>
      <header>
        <meta charset="utf-8" />
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" href="apple-touch-icon.png" />
        <link rel="stylesheet" href="css/normalize.css" />
        <link rel="stylesheet" href="css/main.css" />
        <title></title>
      </header>
      <main>
        {this.props.navbar}
        {this.props.content}
        {this.props.footer}
      </main>
      <footer>
      </footer>
    </div>
  }
});
```

//router.jsx
FlowRouter.route('/', {
  action: function (params) {
    ReactLayout.render(MainLayout, {
      navbar: <Navbar />,
      content: <CommentBox />,
      footer: <Footer />
    });
  }
});

I added the `/>` closing tags to `<meta>` and `<link>` which removes the errors in my terminal, but I don't see them when viewing the source in the browser.

Any ideas?

**Comment by arunoda** [comment]
Just wait. We are working on a project called DocHead to have these.
Releasing on next wednesday :)
Hope you can wait .

**Comment by nicholasalanbrown** [comment]
I can wait, not a problem.

How would I include a package normally invoked via a `{{> }}` such as sacha:spin (i.e. `{{> spin}}}`?

**Comment by arunoda** [comment]
Check the [DocHead](https://github.com/kadirahq/meteor-dochead) project.
