### ISSUE TITLE
Components does not unmount upon route transition

### ISSUE THREAD

**Issue by madshargreave** [kadirahq/meteor-react-layout#6]
I have two routes, however, each of the `content` components does not unmount upon changing route, as evidenced by logging `componentDidUnmount`.

This is problematic because I set up intervals that sync data between my database and external services, but this should only run on the `/feed` route. But without the unmount callback, I don't see how I can clear them in a non-hacky way

```
memberRoutes.route('/feed', {
  action: function() {
    ReactLayout.render(DashboardLayout, {
      content: <Feed/>
    });
  }
});

memberRoutes.route('/publish', {
  action: function() {
    ReactLayout.render(DashboardLayout, {
      content: <Publish/>
    });
  }
});
```

**Comment by arunoda** [comment]
There is no such lifecycle method called `componentDidUnmount`. It needs to be `componentWillUnmount`.

Check here: https://facebook.github.io/react/docs/component-specs.html
