### ISSUE TITLE
Best Place to Store Logged in State?

### ISSUE THREAD

**Issue by nicholasalanbrown** [kadirahq/meteor-react-layout#7]
Hello:

I'm trying to figure out the best way to use this layout manager to store logged in state. Many components need to have a `this.props.user` (i.e. `Meteor.user()`) but this sits at the layout level, not at the individual component level (i.e. `<Navbar />`, etc.). Where should I put the `getMeteorData``call for this, in an``<AppLayout />``` component or something? That would seem to defeat the purpose of using a layout manager at all....any guidance would be much appreciated!

**Comment by arunoda** [comment]
Components are normally arrange as a tree. In the top layer(s) of components you use `getMeteorData` and reactive data to build the data. Then you pass them as props to the components below. You can do that for `Meteor.user()` status as well.

Try to keep lower level of components as pure as possible as you can.
