### ISSUE TITLE
render html tags or markdown from db

### ISSUE THREAD

**Issue by the-evgenii** [kadirahq/meteor-react-layout#9]
Hello! How i can render html or markdown without translate tags to text? I try add marked to react component, render anything rendered to text

```
FlowRouter.route("/", {
    action: function () {
        ReactLayout.render(HomePage);
    }
});


{marked(this.data.page.content)}
```

**Comment by arunoda** [comment]
Check this: https://facebook.github.io/react/tips/dangerously-set-inner-html.html

**Comment by the-evgenii** [comment]
thx arunoda!
